from __future__ import annotations

import json
import os
import re
import base64
import io
from typing import Any

import cv2
import requests
from PIL import Image


DEFAULT_EMOTION_LLAMA_API_URL = os.getenv("EMOTION_LLAMA_API_URL", "http://127.0.0.1:7889/api/predict/")
FALLBACK_EMOTION_LLAMA_API_URL = "http://127.0.0.1:7860/api/predict/"


def _extract_json(text: str) -> dict[str, Any] | None:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{[\s\S]*\}", text)
    if not match:
        return None


def _first_frame_base64(video_path: str) -> str:
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError(f"Cannot open video: {video_path}")

    ok, frame = cap.read()
    cap.release()
    if not ok or frame is None:
        raise ValueError(f"Could not read first frame from video: {video_path}")

    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(frame_rgb)
    buffer = io.BytesIO()
    pil_img.save(buffer, format="PNG")
    return base64.b64encode(buffer.getvalue()).decode("utf-8")

    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def _query_emotion_llama(video_path: str, prompt: str, timeout: int = 240) -> tuple[str, str]:
    frame_b64 = _first_frame_base64(video_path)
    payload_candidates = [
        {"data": [video_path, prompt]},
        {"data": [frame_b64, prompt]},
    ]

    last_error: Exception | None = None
    candidate_urls = [DEFAULT_EMOTION_LLAMA_API_URL]
    if FALLBACK_EMOTION_LLAMA_API_URL not in candidate_urls:
        candidate_urls.append(FALLBACK_EMOTION_LLAMA_API_URL)

    body: Any = None
    used_api_url = DEFAULT_EMOTION_LLAMA_API_URL
    for api_url in candidate_urls:
        for payload in payload_candidates:
            try:
                response = requests.post(api_url, json=payload, timeout=timeout)
                response.raise_for_status()
                body = response.json()
                used_api_url = api_url
                break
            except Exception as exc:
                last_error = exc
        if body is not None:
            break

    if body is None:
        raise RuntimeError(f"Emotion-LLaMA API call failed: {last_error}")

    if isinstance(body, dict) and isinstance(body.get("data"), list) and body["data"]:
        return str(body["data"][0]), used_api_url

    return str(body), used_api_url


def analyze_video_signal(video_path: str) -> dict:
    if not os.path.exists(video_path):
        raise ValueError(f"Video not found: {video_path}")

    prompt = (
        "[reason] Analyze this interview video. Return ONLY JSON with keys: "
        "tone, engagement, body_language, presence_score, engagement_score, confidence, evidence. "
        "Scores must be 0-10. confidence must be 0-1."
    )
    raw, used_api_url = _query_emotion_llama(video_path, prompt)
    parsed = _extract_json(raw) or {}

    tone = str(parsed.get("tone", "Unknown from Emotion-LLaMA output."))
    engagement = str(parsed.get("engagement", "No explicit engagement description returned."))
    body_language = str(parsed.get("body_language", "No explicit body-language signal returned."))

    try:
        presence_score = float(parsed.get("presence_score", 5.0))
    except (TypeError, ValueError):
        presence_score = 5.0
    try:
        engagement_score = float(parsed.get("engagement_score", 5.0))
    except (TypeError, ValueError):
        engagement_score = 5.0
    try:
        confidence = float(parsed.get("confidence", 0.6))
    except (TypeError, ValueError):
        confidence = 0.6

    presence_score = max(0.0, min(10.0, presence_score))
    engagement_score = max(0.0, min(10.0, engagement_score))
    confidence = max(0.0, min(1.0, confidence))

    return {
        "tone": tone,
        "engagement": engagement,
        "body_language": body_language,
        "visual_metrics": {
            "source": "emotion_llama_api",
            "presence_score": round(presence_score, 2),
            "engagement_score": round(engagement_score, 2),
            "confidence": round(confidence, 2),
            "api_url": used_api_url,
        },
        "evidence": parsed.get("evidence", raw),
        "summary": "Video branch analysis generated by local Emotion-LLaMA API.",
    }
